all:
  vars:
    control_plane_endpoint: 192.168.0.100
    load_balancer_ip_pool:
      - 192.168.0.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.109, mac: '00:23:24:d1:f5:69', disk: nvme0n1, network_interface: enp42s0}
    workers:
      hosts:
        metal1: {ansible_host: 192.168.0.102, mac: 'a8:a1:59:5a:40:d2', disk: sda, network_interface: enp4s0}
