elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.aniketkotal.me"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.aniketkotal.me
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.aniketkotal.me
      server_name: aniketkotal.me

dendrite:
  dendrite_config:
    global:
      server_name: matrix.aniketkotal.me
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.aniketkotal.me
    tls:
      - hosts:
          - matrix.aniketkotal.me
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
